defaults: &defaults
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: rubycommitters_development

test:
  <<: *defaults
  database: rubycommitters_test

production:
  <<: *defaults
  database: rubycommitters_production
